name: release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-all:
    runs-on: windows-latest
    name: 'Build executable and package'
    env:
      CXX: "cl"
      VCPKG_DEFAULT_TRIPLET: "x64-windows-static-md"
      VCPKG_DEFAULT_HOST_TRIPLET: "x64-windows-static-md"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v7
        with:
          submodules: 'true'

      - uses: lukka/get-cmake@latest

      - name: "Prepare Windows environment"
        uses: ilammy/msvc-dev-cmd@v1.13.0
        with:
          arch: win64

      - uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: vcpkg.json

      - name: Build and package
        run: |
          cmake --preset ninja 
          cmake --build --preset ninja
          cpack --preset ninja

      - name: Create release and upload assets
        shell: pwsh
        run: |
          $tag_name = "${{ github.ref_name }}"
          gh release create "$tag_name" "./builds/ninja/Manhunt2FSBanker-*.7z"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
